dash doesn't support pattern substitution.  revered to using tr while still keeping things quick.

diff --git a/bin/sshove b/bin/sshove
--- a/bin/sshove
+++ b/bin/sshove
@@ -96,22 +96,22 @@ randstr() {
   # Length of the random string we need to generate.
   randstr_len=${2};
 
-  # Our random string as we generate it.
-  randstr_val='';
-
-  while [ "${#randstr_val}" -lt "${randstr_len}" ]; do
-    read line < /dev/urandom;
-
-    # Append the usable characters to $randstr_val.
-    randstr_val=${randstr_val}${line//[^A-Za-z0-9]/};
-
-    # Trim down to $randstr_len characters.  If the string is not long enough,
-    # all charaters will be kept.
-    randstr_val=${randstr_val:0:${randstr_len}};
-  done;
+  tr -cd "${upper}:${lower}:${number}" < /dev/urandom | \
+  dd of="${tmpdir}/read.${pid}" count=1 bs=${randstr_len} 2>/dev/null
+  read randstr_val < "${tmpdir}/read.${pid}"
 
   eval $randstr_var=$randstr_val;
   return 0;
+}
+
+agent() {
+  SSH_AUTH_SOCK=${SSH_AUTH_SOCK:=${sshagent_socket}};
+  export SSH_AUTH_SOCK;
+
+  ${sshagent_command} -a "${sshagent_socket}" >/dev/null 2>&1;
+  if ! "${sshadd_command}" -l >/dev/null 2>&1; then
+    "${sshadd_command}";
+  fi;
 }
 
 # If we can't stat $script_path, it must have come from $PATH.  Let's find
@@ -156,8 +156,23 @@ rsyncd_pidfile=${rsyncd_pidfile:-"${tmpdir}/rsyncd.pid"};
 rsyncd_port=${rsyncd_port:-'1897'};
 rsync_filter=${rsync_filter:-"${tmpdir}/rsync.filter"};
 rsync_dirfilter=${rsync_dirfilter:-".${program}.filter"};
+sshagent_command=${sshagent_comand:='ssh-agent'};
+sshagent_socket=${sshagent_socket:=${tmpdir}/.ssh-agent.sock};
+sshadd_command=${sshadd_comand:=ssh-add};
+use_sshagent=${use_sshagent:-1};
 [ -z "${rsyncd_user}" ] && randstr rsyncd_user 8;
 [ -z "${rsyncd_pass}" ] && randstr rsyncd_pass 8;
+
+# Clean up our paths.
+for var in source_path tmpdir rsync_logfile include_file exclude_file \
+    rsyncd_config rsyncd_passwd rsyncd_pidfile rsync_filter sshagent_socket; do
+  rpath $var;
+done
+
+# Make sure ssh-agent is running
+if [ "${use_sshagent}" = '1' ]; then
+  agent;
+fi;
 
 # If we have anything other than exactly 1 argument, then just call ssh as we
 # we don't know what arguments might be necessary to preform our rsync.
@@ -168,7 +183,7 @@ fi;
 
 # Make sure our $config_base and $tmpdir exist. 
 for var in config_base tmpdir; do
-  rpath $var dir;
+  eval dir=\$$var;
   if ! [ -d "${dir}" ]; then
     if ! mkdir -m 700 "${dir}"; then
       echo "error: '${dir}' does not exist and could not be created" >&2;
@@ -180,10 +195,9 @@ done;
 filters="dir-merge ${rsync_dirfilter}${newline}";
 
 # We always exclude our tmp directory and files.
-rpath source_path base;
 for name in tmpdir rsyncd_pidfile rsyncd_config rsyncd_passwd rsync_filter; do
-  # Get the rpath and the strip off our prefix.
-  rpath $name value; value="${value#${base}}";
+  # Strip off our prefix.
+  eval value=\$$name; value="${value#${source_path}}";
 
   # Add this to our excludes.
   filters="${filters}- ${value}${newline}";
